{"name": "用户名密码都错误进行登录", "status": "passed", "attachments": [{"name": "stdout", "source": "63c478f5-89c0-4767-b23c-47df9b97045d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "(5, 'http://39.98.138.157:5000', '/api/login', 'post', None, '{\"username\":\"admin123\",\"password\":\"111111\"}', 'json', '$..msg', '用户名或密码错误', '通过', '用户名密码都错误进行登录', None, None, None, None, 'F01_S01_登录', 'F01_用户管理', None, 'normal')"}], "start": 1657205313339, "stop": 1657205313510, "uuid": "7716bbad-e81f-42fe-8e3b-02bbee6e21d5", "historyId": "eee9eb4c0b6c790a6b594b90b01b148e", "testCaseId": "a86f64a292a32ac87873c420936468de", "fullName": "case.test_Excel#test_01", "labels": [{"name": "story", "value": "F01_S01_登录"}, {"name": "feature", "value": "F01_用户管理"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_Excel"}, {"name": "host", "value": "DESKTOP-LUOD4RE"}, {"name": "thread", "value": "12192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_Excel"}]}