{"name": "用户名错误登录", "status": "passed", "attachments": [{"name": "stdout", "source": "6275397b-2df6-4350-87f5-23f1ae3d21a8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "(4, 'http://39.98.138.157:5000', '/api/login', 'post', None, '{\"username\":\"admin123\",\"password\":\"123456\"}', 'json', '$..msg', '用户名或密码错误', '通过', '用户名错误登录', None, None, None, None, 'F01_S01_登录', 'F01_用户管理', None, 'normal')"}], "start": 1657205313179, "stop": 1657205313329, "uuid": "ea6204fa-457f-4959-ad00-43cb2b2c5ecd", "historyId": "e7837b8998a47678d2cfa92c3d3ee9df", "testCaseId": "a86f64a292a32ac87873c420936468de", "fullName": "case.test_Excel#test_01", "labels": [{"name": "story", "value": "F01_S01_登录"}, {"name": "feature", "value": "F01_用户管理"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_Excel"}, {"name": "host", "value": "DESKTOP-LUOD4RE"}, {"name": "thread", "value": "12192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_Excel"}]}